#pragma once

#include "axpy.cuh"
#include "broadcast.cuh"
#include "count.cuh"
#include "cross_decomp.cuh"
#include "elementwise.cuh"
#include "fill.cuh"
// #include "ktruss_binary.cuh"
// #include "ktruss_serial.Incremental.cuh"
// #include "ktruss_serial._inc_loop.cuh"
// #include "ktruss_serial.cuh"
#include "load_balance.cuh"
// #include "merge_path.cuh"
#include "reduction.cuh"
#include "search.cuh"
#include "tc_edge_binary.cuh"
#include "tc_edge_dyn.cuh"
#include "tc_edge_dynpar.cuh"
#include "tc_edge_linear.cuh"
#include "tc_vertex_bitvector.cuh"
// #include "tc_edge_merge.cuh"
#include "tc_vertex_block_binary.cuh"
#include "tc_vertex_blocks_binary.cuh"
#include "tc_vertex_blocks_cache_block_binary.cuh"
#include "zero.cuh"
