language: minimal
dist: trusty
sudo: true
services:
- docker
  
env:
  global:
    - RAI_ROOT=${HOME}/.rai
matrix:
  include:
    - env: DOCKER_CUDA=100 DOCKER_ARCH=amd64

script:
- cd ${TRAVIS_BUILD_DIR}
- ./ci/build_and_push_docker.sh