language: minimal

jobs:
  include:
    # 18.04 amd64 cuda-10-2 RELEASE
  - dist: bionic
    arch: amd64
    env:
      - CUDA_VERSION=102
      - BUILD_TYPE=Release
    # 18.04 amd64 cuda-10-2 DEBUG
  - dist: bionic
    arch: amd64
    env:
      - CUDA_VERSION=102
      - BUILD_TYPE=Debug
    # 18.04 ppc64le cuda-10-2 RELEASE
  - dist: bionic
    arch: ppc64le
    env:
      - CUDA_VERSION=102
      - BUILD_TYPE=Release
    # 16.04 ppc64le cuda-10-2 RELEASE
  - dist: trusty
    arch: amd64
    env:
      - CUDA_VERSION=102
      - BUILD_TYPE=Release

cache:
  directories:
    $HOME/cmake

install:
  - ci/install.sh || travis_terminate 1;

script:
  - ci/script.sh || travis_terminate 1;