# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    mkdir -p $HOME/bin
    export PATH="$HOME/bin:$PATH"
  displayName: 'make $HOME/bin'

- script: |
    sudo apt-get update
    sudo apt-get install -y --no-install-suggests --no-install-recommends -y \
    curl \
    libnuma-dev 
  displayName: 'Install curl'

- script: |
    curl -SLO https://github.com/Kitware/CMake/releases/download/v3.14.3/cmake-3.14.3-Linux-x86_64.sh
    chmod +x cmake-3.14.3-Linux-x86_64.sh
    sudo ./cmake-3.14.3-Linux-x86_64.sh --skip-license --prefix="$HOME"
    ls $HOME/bin
  displayName: 'Install CMake'

- script: |
    curl -SLO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.1.105-1_amd64.deb
    sudo dpkg -i cuda-repo-ubuntu1604_10.1.105-1_amd64.deb
    sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    sudo apt-get update
    sudo apt-get install cuda-command-line-tools-10-1
  displayName: 'Install CUDA'

- script: |
    which cmake
    cmake --version
    mkdir build
    cd build
    cmake ..
  displayName: 'configure'

- script: |
    make
  displayName: 'build'

- script: |
    make test
  displayName: 'test'