# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y --no-install-suggests --no-install-recommends -y \
    curl \
    libnuma-dev 
  displayName: 'Install curl'

- script: |
    curl -SLO https://github.com/Kitware/CMake/releases/download/v3.14.3/cmake-3.14.3-Linux-x86_64.sh
  displayName: 'Download CMake'

- script: |
    chmod +x cmake-3.14.3-Linux-x86_64.sh
    sudo ./cmake-3.14.3-Linux-x86_64.sh --skip-license
  displayName: 'Install CMake'

- script: |
    cmake --version

- script: |
    mkdir build
    cd build
    cmake ..
  displayName: 'configure'

- script: |
    make
  displayName: 'build'

- script: |
    make test
  displayName: 'test'