#spdlog 1.2.1 uses fmt 5.2.1
hunter_config(spdlog VERSION 1.2.1-p0 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON SPDLOG_FMT_EXTERNAL=ON)
hunter_config(fmt VERSION 5.2.1 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON)